feature: add callback url to job params
Smartling/api-sdk-nodejs pull request #94
Opened 2023-11-13 13:51 UTC by fllprbt

2023-11-14 11:20 UTC, PavelLoparev commented
Hi @fllprbt, it appears Files API doc is wrong about having `zipFileName` query parameter for `download all translations` [endpoint](https://api-reference.smartling.com/#tag/Files/operation/downloadTranslatedFilesAllLocales). We will fix the doc.

This param should be removed from the `DownloadFileAllTranslationsParameters`. If you try to download without that param it api will respond with `application/zip;charset=UTF-8` response like:
```
curl --location 'https://api.smartling.com/files-api/v2/projects/<projectId>/locales/all/file/zip?fileUri=<fileName>.<fileExtension>' \
--header 'Authorization: Bearer ...'

PK  � nW               zh-CN/<fileName>.<fileExtension>��<?xml version="1.0" encoding="UTF-8"?>
<zh-CN file content here>
PKg���    PK  � nW               da-DK/<fileName>.<fileExtension>��<?xml version="1.0" encoding="UTF-8"?>
<da-DK file content here>
...
```
And then you probably can save it as you need (didn't dig deeper, I just checked this sdk method returns exactly the same content as curl/postman call)

2023-11-14 11:22 UTC, PavelLoparev commented
> Is writing non-raw responses supported atm?
For now it supports to receive raw response body as `response.text()` or parsed dtos from response json.

2023-11-15 15:56 UTC, dimitrystd commented
Hi All,
I didn't review the PR, but the `zip` word caught my attention. I strongly recommend not using zip in integrations. Because TMS must prepare all translated files before actual download, downloading a zip file may increase response time. When the user interacts with TMS, using zip makes sense. However, for automation, robustness is the top priority. Tens of short HTTP requests (with predictable response time) are preferable to one request when response time can range from seconds to minutes. 

P.S. @conall-smartling for visibility. There are a couple of related tickets #89, #92.

2023-11-17 04:49 UTC, fllprbt commented
> Hi @fllprbt, it appears Files API doc is wrong about having `zipFileName` query parameter for `download all translations` [endpoint](https://api-reference.smartling.com/#tag/Files/operation/downloadTranslatedFilesAllLocales). We will fix the doc.
> 
> This param should be removed from the `DownloadFileAllTranslationsParameters`. If you try to download without that param api will respond with `application/zip;charset=UTF-8` response like:
> 
> ```
> curl --location 'https://api.smartling.com/files-api/v2/projects/<projectId>/locales/all/file/zip?fileUri=<fileName>.<fileExtension>' \
> --header 'Authorization: Bearer ...'
> 
> PK��������� nW����������������zh-CN/<fileName>.<fileExtension>�����<?xml version="1.0" encoding="UTF-8"?>se
> <zh-CN file content here>
> PK��g�����������PK��������� nW����������������da-DK/<fileName>.<fileExtension>�����<?xml version="1.0" encoding="UTF-8"?>
> <da-DK file content here>
> ...
> ```
> 
> And then you probably can save it as you need (didn't dig wdeeper, I just checked this sdk method returns exactly the same content as curl/postman 


Right, i also had glyphs previous week when i had tested it; had tried to parse it as zip and failed.

2023-11-24 17:06 UTC, fllprbt commented
@PavelLoparev could you review this MR please? Added also the list batches helper

2023-11-27 10:13 UTC, PavelLoparev commented
Hi @fllprbt, could you please remove `zipFileName` query parameter from `DownloadFileAllTranslationsParameters` class?

2023-11-27 10:27 UTC, PavelLoparev requested changes
Hi @fllprbt, could you please remove `zipFileName` query parameter from `DownloadFileAllTranslationsParameters` class?

looks ok other than that

2023-11-27 12:16 UTC, fllprbt commented
done!

2023-11-27 22:16 UTC, fllprbt commented
Done, btw we would like eventually something similar here: https://github.com/Smartling/api-sdk-nodejs/blob/master/api/jobs/index.ts#L57C63-L57C85

 Since a params object can be passed, does it mean that we can use `params.set` to set these manually in case the specific helpers do not exist?

2023-11-28 17:08 UTC, PavelLoparev approved these changes

2023-11-28 17:11 UTC, PavelLoparev commented
> Done.
> 
> Btw we would like eventually have something similar here: https://github.com/Smartling/api-sdk-nodejs/blob/master/api/jobs/index.ts#L57C63-L57C85
> 
> Since a params object can be passed, does it mean that we can use `params.set` to set these manually in case the specific helpers do not exist?

yes, you can use `.set()` method but I would prefer to just to add anything that is missing/needed for you through the PRs.

2023-11-28 17:12 UTC, merged

2023-11-28 17:22 UTC, PavelLoparev commented
`2.4.0` is released

2023-12-05 13:38 UTC, cipsicko commented
Hi, the `setCallbackUrl` method was added without `setCallBackMethod` that is mandatory otherwise an error occurs.
https://api-reference.smartling.com/#tag/Jobs/operation/addJob

2023-12-05 13:47 UTC, fllprbt commented
> Hi, the `setCallbackUrl` method was added without `setCallBackMethod` that is mandatory otherwise an error occurs. https://api-reference.smartling.com/#tag/Jobs/operation/addJob

Sorry, missed that from docs. Can fix myself this Friday if not anyone else does

2023-12-06 11:09 UTC, cipsicko commented
> > Hi, the `setCallbackUrl` method was added without `setCallBackMethod` that is mandatory otherwise an error occurs. https://api-reference.smartling.com/#tag/Jobs/operation/addJob
> 
> Sorry, missed that from docs. Can fix myself this Friday if no anyone else does

I can do it but i'm stucked here https://github.com/Smartling/api-sdk-nodejs/issues/95

2024-01-04 14:54 UTC, PavelLoparev commented
This is going to be addressed in https://github.com/Smartling/api-sdk-nodejs/pull/100

2024-09-30 14:41 UTC, PavelLoparev commented
As for downloading zip: https://github.com/Smartling/api-sdk-nodejs/pull/117